### ISSUE TITLE
Cannot use localStorage with DatePicker

### ISSUE THREAD

**Issue by hyouuu** [elm-community/elm-datepicker#21]
When I try to store model info into localStorage, compiler complains:

port setStorage : Model -> Cmd msg
The specific unsupported type is:

    DatePicker.DatePicker

The types of values that can flow through in and out of Elm include:

    Ints, Floats, Bools, Strings, Maybes, Lists, Arrays, Tuples, Json.Values,
    and concrete records.

Is there a way to get around it? Thanks!

**Comment by bbqbaron** [comment]
As the code stands, I don't think there is. The reason (you may already know, sorry if I over-explain) is that Elm can't send records that are wrapped in a type tag like `DatePicker` through ports. What would need to happen is to unwrap it before it hits the port with something like 

```
case model of 
  DatePicker datePicker ->
    datePicker
```

buuuut this module doesn't currently expose the actual `DatePicker` tag (although it does expose the `DatePicker` _type_ itself.

The Elm API guidelines often discourage exposing your type constructors, which leaves us with a conundrum! I'm actually gonna ask on Elm Slack for a more experienced API designer's instincts. Back soon!

**Comment by sporto** [comment]
Try to persiste the date picker state is not a good idea, as this state is meant to be internal and can change with new versions.  Many Elm components use this internal state pattern, so you are likely to run intro trouble doing this. Try saving only the `date` in your model.

**Comment by hyouuu** [comment]
Thanks for the info! Do you have an example using the DatePicker without putting it into model @sporto ?

**Comment by sporto** [comment]
@hyouuu 	you still need to put the datepicker model into your main model. But you will need to filter  that out before sending your model to localStorage.

**Comment by hyouuu** [comment]
Ah I see - how do I do that? I'm a newbie...

**Comment by sporto** [comment]
You will need to extract the serializable attributes from your model, as far as I know the only way to do this is something like:

```elm
serializableModel model =
	{ date = model.date
	, x = model.x
	, y = model.y
	, ...
	}
```

So picking the serializable attrs one by one.

**Comment by hyouuu** [comment]
Thanks!!

**Comment by bbqbaron** [comment]
Sporto is my hero. Closing.
