### ISSUE TITLE
Access internal state (open: Bool)

### ISSUE THREAD

**Issue by A5308Y** [elm-community/elm-datepicker#24]
Hi there!

I'm having some trouble with the DatePicker.

I have some timers in my app, that update the model every second.

When I try to change the value of the DatePicker's text field it gets reset, prohibiting me from entering dates as text. I can only select dates from the DatePicker.

Omitting the update whenever the DatePicker is open would solve the problem for me, but I'm unable to access the DatePicker's internal state. I posted my question in Slack and it was confirmed that it's not possible to get the value of open, even though the debugger can display the complete internal state.

Did we overlook a way to get to the value of open?
If not, would you consider exposing it?

Thanks for your great work by the way! I'm happily using the DatePicker everywhere in my app! 😄

**Comment by bbqbaron** [comment]
Hello! Terribly sorry for the delay. I was traveling, which created a bit of a backlog. I'll get to this in the next day.

**Comment by A5308Y** [comment]
@bbqbaron No worries! Thanks for your reply!

**Comment by bbqbaron** [comment]
I'm back. So to your direct question (`Did we overlook a way to get to the value of open?`) I think the answer is no--I don't see a way either.

The use case sounds interesting, so I have a few clarifying questions: When you say `prohibiting me from entering dates as text`, why is it that you need to enter them as text? Can you set the `pickedDate` on the `Settings` record that you pass to the datepicker? What text is being entered that could not be parsed as a date?

It would be easy to expose `open`, but it sounds like we'd be doing it in order to enable directly manipulating DOM elements inside the picker. This seems like it could create a dependence on internal details (like the picker's DOM structure) that aren't part of its API.

Does that make sense? I may just not have enough background on your use case.

**Comment by A5308Y** [comment]
Hi @bbqbaron! Thanks for your answers!

I just realized I didn't describe my problem very well:

What I mean with "reset" is that I can't change the datepicker's input field at all:

![datepickerreset](https://cloud.githubusercontent.com/assets/226510/24069897/6bd5ae18-0bb3-11e7-8ff6-a21a46be5100.gif)

What I am expecting is to be able to change the date by changing values in the text field without clicking on the datepicker:

![datepickerfixed](https://cloud.githubusercontent.com/assets/226510/24070039/50c87450-0bb5-11e7-94e8-ae6fea3241a4.gif)

My explanation of what happens during a "reset":
* I start editing the date in the input-field
* The timerUpdate is triggered, updating a couple of records in my main model
* This leads to a new model with a newly initialized datepickerModel discarding all inputs from the last second

The possible solutions I came up with are:
1. **Initialize the datepicker with the newly entered text input**
I couldn't get this to work because the `onInput` happens in the Datepicker's code and model. Only when I properly select a date by clicking or hitting "enter" or "tab" is the exposed `date` updated (Or did I get that wrong?). I didn't find a way to intercept/access the entered text to store it for the next initialization of the Datepicker. I couldn't set the pickedDate because the input kind of "bypassed" my app.

2. **Disable the timerUpdate whenever someone is using the Datepicker**
For this I need to know when not to update. Not updating the timers for a few seconds while users are focussed on choosing a date seemed ok for me. This lead me to try figuring out when the datePicker is open.

I might very well be doing something wrong here. If you have other solutions I'm happy to try them.

Thanks for reading (and for maintaining the datePicker 😃 )!

**Comment by bbqbaron** [comment]
Thank you for the extensive report; it's very helpful. What I think is fundamentally wrong is that the picker resets the text field to the picked date with each render and has no internal notion of text-in-progress. Exposing `isOpen` would enable you to get around it, but I think the picker's data model is actually basically incorrect. It needs to understand as part of its state that the user could be midway entering some possible, eventual date, and it shouldn't eagerly rewrite the text field with the last picked date all the time.

Does that sound correct? What's your timeline for the fix? Mind if I chew on it a bit and try to find the most elegant restructuring of the model?

**Comment by A5308Y** [comment]
That sounds fabulous! It would solve my problem completely and without any code changes on my part. I didn't even think of that as a responsibility of the Datepicker, but I think you're right and this would actually be "the correct place" to fix the problem.

It's not urgent, but I would be thankful if it could be fixed until mid-April. Does that sound like enough time for elegance?

**Comment by bbqbaron** [comment]
Goodness yes, that's plenty of time. I'm hoping for the next couple of days.

**Comment by bbqbaron** [comment]
What do you think of #28 ? It's of course not your problem to make the internals work right :), but I figured I'd at least offer it for comment and/or trying locally to make sure it actually fixes your use case! Barring that, I'll poke at it a bit more, and probably merge it soon.

**Comment by A5308Y** [comment]
@bbqbaron Did you see my comments on #28? I hope I'm not making things too complicated...

**Comment by bbqbaron** [comment]
@A5308Y Not at all! I appreciate the feedback. Anyway, busy week; I'm having a look now. More comments on PR when I have results, but TLDR I agree with you that live updates feel the most helpful in terms of UI feedback. Configuring it to be live or not sounds like scope creep, so I may just go with the original live-updates change and make a note in the new version README.
