### ISSUE TITLE
Cannot understand how any function that requires the Model can be used

### ISSUE THREAD

**Issue by julianjelfs** [elm-community/elm-datepicker#26]
For example when I have an instance of the DatePicker type as returned by init, how can I then call getDate in order to obtain the Maybe Date value? getDate requires a Model which is not what I have. 

Without being able to understand how to call getDate, setDate or setFilter I really can't work out how to synchronise two date pickers into a range. 

Would really appreciate some help (if I am missing something) or some clarification if a fix of some kind is required. 

Happy to help if I can by the way.

**Comment by bbqbaron** [comment]
I'm glad you noticed that too! It occurred to me recently that those functions wouldn't do anyone any good. You're not missing anything; I think a (hopefully fairly simple) fix is in order to convert them to `DatePicker ->` instead of `Model ->`. I'll certainly get to it soon if no one else does.

**Comment by julianjelfs** [comment]
Hey, if you're happy with that change to the interface, I'm happy to have a go at making that change myself and send you a PR. I'm keen to get involved because I think there are a number of enhancements that we would like to make in the future (keyboard control, multi-month views, internationalisation etc) so it would be good to get familiar with things.
