### ISSUE TITLE
How do I pick _no_ date?

### ISSUE THREAD

**Issue by bbqbaron** [elm-community/elm-datepicker#29]
`update` returns `, Maybe Date)`, in which `Nothing` signals that the date _has not changed_. What if I want to pick no date at all, by say blanking out the text field? I can make `DatePicker` respond correctly, but external `update` listeners won't be able to tell.

**Comment by julianjelfs** [comment]
I must say that personally I think the update function returning Nothing to signal that the date has not changed makes for a confusing api. I think it would be better if it always returned the selected date. It's a breaking change of course, but it definitely feels better to me.
