### ISSUE TITLE
Choosing a different default start date when pickedDate is Nothing

### ISSUE THREAD

**Issue by cazgp** [elm-community/elm-datepicker#36]
If pickedDate is Nothing, when choosing a date, the default date is the 29th May 1992.

Is it possible to provide an alternative `initDate` function, or to expose something in the settings to allow this be different?

**Comment by bbqbaron** [comment]
Thanks for the PR! `init` dispatches a `Date.now`, so if the command is correctly returned to the component, presumably `5/29/92` shouldn't last very long!

I just want to clarify whether that addresses your need or not: is it that you want to be able to specify what date the picker centers on when opened, _without_ just picking a date to start on? I.e. "Your date should probably be in May 2015, but something bad would happen if I preselected 5/15/15?"

**Comment by michaeljones** [comment]
Hi, I'm a colleague of @cazgp. Thanks for the quick and considerate response. You're right. I've just been looking at it now and we hadn't wired up the initial commands/message properly so they were never making it out to get back with the right data.

I'm not 100% what you're asking for in the second paragraph but I think that the datepicker is working fine for our needs when we wire it up properly. 

Thanks again.

**Comment by bbqbaron** [comment]
My pleasure!
