### ISSUE TITLE
`update` always returns `Cmd.none`

### ISSUE THREAD

**Issue by charles-cooper** [elm-community/elm-datepicker#40]
Based on my reading of https://github.com/elm-community/elm-datepicker/blob/4.0.0/src/DatePicker.elm#L230-L299, `DatePicker.update` always returns `Cmd.none`. This results in a confusing API because a consumer of the API has to implement extra code to deal with the returned `Cmd` -- even though it always ends up being a no-op. Would it be appropriate to remove the `Cmd` from the return value of the `update` function?

**Comment by bbqbaron** [comment]
Good eye. The reason why we retain the `Cmd` is that it's common for opaque Elm components to have `update: Msg -> Model -> (Model, Cmd Msg)`, which makes it idiomatic. I'm not zealously opinionated, and I see what you mean about the extra code, but here are the two reasons why I think we should keep it:

* `init` returns a `Cmd` (an important one!) so we've introduced the idea that this component has _some_ kind of opaque `Cmd`-based lifecycle.
* `update returns a 3-tuple, meaning that it's already necessary to unwrap the return value of `update`. At that point, retaining the second member just for consistency with other components seems low cost.

Does that seem reasonable? Was the intent to merely ask the question, such that I should close this?
