### ISSUE TITLE
can't use datepicker after installation

### ISSUE THREAD

**Issue by noiseOnTheNet** [elm-community/elm-datepicker#46]
I'm using the elm 0.18 platform; the installation completes without errors
```

elm package install elm-community/elm-datepicker
To install elm-community/elm-datepicker I would like to add the following
dependency to elm-package.json:

    "elm-community/elm-datepicker": "6.0.0 <= v < 7.0.0"

May I add that to elm-package.json for you? [Y/n] 

Some new packages are needed. Here is the upgrade plan.

  Install:
    elm-community/elm-datepicker 6.0.0

Do you approve of this plan? [Y/n] 
Starting downloads...

  ● elm-community/elm-datepicker 6.0.0

Packages configured successfully!
```

 but as soon as I use elm make I get this message

```
The elm-package.json constraints of 'elm-community/elm-datepicker' are probably
letting too much stuff through. Definitely open an issue on the relevant github
repo to get this fixed and save other people from this pain.
```

**Comment by bbqbaron** [comment]
If I only run:

> elm-package install elm-community/elm-datepicker
> elm-make

in an empty directory, it builds OK.

I see a few GH issues mentioning this error; in each case it looks like some flavor of clear-and-retry solved the problem (see [here](https://github.com/elm-lang/virtual-dom/issues/58), [here](https://github.com/elm-lang/core/issues/449), [here](https://github.com/debois/elm-mdl/issues/253)). Could you either:

* try auditing your `elm-package.json` and retrying installation
* providing an example codebase that fails, if that doesn't work?

Thanks!

**Comment by noiseOnTheNet** [comment]
I created a simple example 
```
module Test exposing (main)

import DatePicker
import Html exposing (div, text)


main =
    div [] [ text "Hello World" ]
```
and tried to compile it with 

`elm make Test.elm --output test.js`

using the same elm-stuff directory of my project.
The compilation now works for this and all other modules: I suppose that something has been cleared into the package system but I can't figure what.

Thank you anyway,
   Marco

**Comment by bbqbaron** [comment]
No problem!
