### ISSUE TITLE
Add ability to quickly change year

### ISSUE THREAD

**Issue by alltonp** [elm-community/elm-datepicker#5]
Hi,

Firstly, thank you for this widget, it looks nice and was very easy to integrate into my app.

Please could you make it possible to change the year quickly. e.g. Right now if I want to change the year to 1984, that's an awful lot of clicking backwards ...

On widgets that I've used previously, clicking on the year allows the user to navigate through the years.

Many thanks,

Paul

**Comment by bbqbaron** [comment]
I believe this was done in #33! Freebies.
