### ISSUE TITLE
Docs for `init` are out-of-date (no longer a function)

### ISSUE THREAD

**Issue by gutierlf** [elm-community/elm-datepicker#54]
The docs for `init` function still refer to a 'Settings record' argument.

https://github.com/elm-community/elm-datepicker/blob/70a84f312718dbc2a1434d309d711980cb66ac4d/src/DatePicker.elm#L205

**Comment by bbqbaron** [comment]
👍 Fixed!

**Comment by gutierlf** [comment]
Fast turnaround! 👏👏
