### ISSUE TITLE
Add a way to clear the datepicker

### ISSUE THREAD

**Issue by twopoint718** [elm-community/elm-datepicker#7]
Thanks for the great widget!

A common thing that I do is once a form is submitted, I clear out the inputs. Are you planning on adding a "clear" or "reset" function to this module?

**Comment by witoldsz** [comment]
Also, sometimes date is just an optional field and there must be a way to clear the field.

**Comment by bbqbaron** [comment]
The model's `pickedDate` is `Maybe Date`, and `setDate` updates `pickedDate` in the model. What if you do something like this during `update`?

`let newPicker = setDate Nothing model.picker
  in  ( { model | picker = newPicker }, Cmd.none )`

**Comment by bbqbaron** [comment]
I would re-init the picker with a `Nothing` date, a la 

```
{ model | datePicker = DatePicker.init { defaultSettings | pickedDate = Nothing }
```

Does that fit your use case?

**Comment by twopoint718** [comment]
@bbqbaron, I'm away from my code at the moment. Does that actually visually clear the widget & have it not submit any value (form value would be empty)?

**Comment by bbqbaron** [comment]
Yes, it does. I tested locally and it seems to work as expected.

**Comment by twopoint718** [comment]
I'm happy to close this issue then if nobody objects
