### ISSUE TITLE
disable datepicker on conditions

### ISSUE THREAD

**Issue by jmarca** [elm-community/elm-datepicker#8]
Hi,  thanks for writing this, it is very useful.

I would like to disable the datepicker under certain conditions, and I am not sure how to do this. 

Specifically, when the UI is fetching data for the chosen date, I would like to freeze the datepicker so that the user cannot change the date until the incoming data has arrived.

I have a flag in my model for this (model.gettingData = True or False) and in my other form elements I can just say Attr.disabled model.gettingData

Is there any similar way to do that with the datepicker, or should I resort to directly manipulating the DOM?

**Comment by Bogdanp** [comment]
I think one way you could achieve this is to re-init the `Datepicker` with `{defaultSettings | isDisabled = always True}` after the user picks a date and then reset it once you're done retrieving data from the server.

**Comment by jmarca** [comment]
Okay thanks I'll try that.  My current work around is an if statement in the view...if (model.gettingData), then I render a plain input field, but disabled.  If not, then I render the datepicker.  That works, but the styling of the two is pretty janky right now, and I'll have to do some work to make the plain-but-disabled-input style match the enabled datepicker style.

My only concern with your suggestion is I *think* what will happen is the datepicker will do a pop-up with all the dates disabled.  That's likely to confuse the user.  My preference is for a solution which ignores mouse actions altogether.

**Comment by bbqbaron** [comment]
Presuming that the need was met, not having heard back; closing for tidiness. Please feel free to report back if there was a problem!

**Comment by jmarca** [comment]
Yeah, I worked around it with a hack.  Sorry, I forgot to report back and close.

Looking at my code and refreshing my memory, what I did was to not render a date picker when I didn't want a date picker:

```
 datepickbuilder : Model -> Html Msg
datepickbuilder model =
    let  y = (toString (Date.year model.date))
         m = (pad (monthToInt (Date.month model.date)))
         d  = (pad (Date.day model.date))
    in
        case model.fetchingColors of
            False -> DatePicker.view model.datePicker
                         |> App.map ToDatePicker
            True -> input [Attr.class "disabled-date form-control"
                           , Attr.disabled True
                           , Attr.name "datepicker"
                           , Attr.value (y++"-"++m++"-"++d)][]

```

In other words, if my client is busy "fetching colors" for a particular date, then render a disabled form element with the current chosen date.  If it is *not* fetching colors, then render the usual datepicker element.  I also tweaked the CSS on the disabled date form element so that the fonts and layout mirror the datepicker.
