### ISSUE TITLE
Pass settings as parameters only in one of update/view

### ISSUE THREAD

**Issue by jjant** [elm-community/elm-datepicker#84]
I'm not sure why we need to pass the settings in both the update and the view, this makes using the datepicker in different files annoying (files dealing with update and views all must import settings).

**Comment by bbqbaron** [comment]
Right now I think it's just that the lib happens to group behavioral settings into one type! A quick scan of the code says most of the fields on `Settings` are really only used in one of `update` or `view`. I think that means we could split them into different types and pass them separately? Is that a good pattern for Elm widget libs that accept behavioral parameters?
